galaxy_info:
  role_name: note_app
  author: davidahdy
  description: A role to deploy a simple Flask note-taking web app
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8

dependencies: []
